version: '3'
services:
  backend:
    image: golang:1.10
    volumes:
      - ./backend:/go/src/main
    working_dir: /go/src/main
    command: "bash -x /go/src/main/start.sh"
    ports:
      - "8080:8080"

  frontend:
    image: node:8
    volumes:
      - ./frontend:/var/www
    working_dir: /var/www
    command: "bash -x /var/www/start.sh"
    ports:
      - "8000:8000"
